services:
  immich-smart-albums:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    environment:
      - IMMICH_SERVER_URL=http://172.17.0.1:2283 # IMPORTANT: Replace with your Docker host IP (e.g., `ip addr show docker0` on Linux)